name: Streamlit Login App (Running on the local machine)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build Docker image
      - name: Build the Docker image
        run: |
          docker build -t login-app . || (echo "Docker build failed!" && exit 1)

      # Step 5: Tag Docker image
      - name: Tag the Docker image
        run: |
          docker tag login-app:latest "${{ secrets.DOCKER_USERNAME }}/login-app:latest"

      # Step 6: Push Docker image to Docker Hub
      - name: Push the Docker image to Docker Hub
        run: |
          docker push "${{ secrets.DOCKER_USERNAME }}/login-app:latest"

      # Step 7: Deploy to EC2
      - name: SSH into EC2 and deploy the app
        env:
          PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.EC2_SERVER_IP }}
        run: |
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          ssh -i private_key.pem ubuntu@$SERVER_IP << EOF
            docker pull "${{ secrets.DOCKER_USERNAME }}/login-app:latest"
            docker stop login-app || true
            docker rm login-app || true
            docker run -d --name login-app -p 8501:8501 "${{ secrets.DOCKER_USERNAME }}/login-app:latest"
          EOF
