name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up SSH for EC2 connection
      - name: Set up SSH keys
        env:
          PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.EC2_SERVER_IP }}
        run: |
          echo "$PRIVATE_KEY" > cicd.pem
          chmod 600 cicd.pem
          chmod 400 cicd.pem
          # Start SSH agent and load the private key
          eval "$(ssh-agent -s)"
          ssh-add cicd.pem

      # Deploy to EC2
      - name: SSH into EC2 and deploy the app
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@$SERVER_IP << EOF
            # Update packages and fix broken dependencies
            sudo apt-get update
            sudo apt --fix-broken install -y
            
            # Install Docker (Ubuntu instructions, for Amazon Linux use dnf)
            sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo tee /etc/apt/trusted.gpg.d/docker.asc
            sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu \$(lsb_release -cs) stable"
            sudo apt-get update
            sudo apt-get install -y docker-ce
            
            # Start Docker service
            sudo systemctl enable docker
            sudo systemctl start docker
            
            # Verify Docker installation
            docker --version
          EOF
