name: streamlit login app (Running on the local machine)
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ${{matrix.os}}
      strategy;
        matrix: 
          os:[ubuntu-latest,windows-latest,macos-latest]
    
    
    steps:
    #This is the step 1 that will execute first (Checkout code)
    -name: Checkout code
    uses: actions/checkout@v3
    
    step:
    # This is step 2 that will execute after step 1 (set up the docker)
    -name: set up Docker 
    uses: docker/setup-buildx-action@v2

    step:
    # This is the step 3 that will execute after step 2 (Build the docker image)
    -name: Build the docker image
    run: | 
      docker build -t login-app .

    step:
    # After creating the image now lets test that docker file
    -name: Test the docker image
    run: | 
      docker run -d -p 8501:8501 login-app
