name: Streamlit Login App (Running on the local machine)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Step 3: Set up Docker Hub login
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build the Docker image
      - name: Build the Docker image and checking the images
        run: |
          docker build -t login-app .
          docker images
          docker tag login-app:latest ${{ secrets.DOCKER_USERNAME }}/login-app:latest

      # Step 5: Push the Docker image to Docker Hub
      - name: Push the Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/login-app:latest

      # Step 6: Test the Docker container
      - name: Test the Docker image
        run: |
          docker run -d -p 8501:8501 ${{ secrets.DOCKER_USERNAME }}/login-app:latest
