name: Streamlit Login App (Running on the local machine)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build the Docker image
      - name: Build the Docker image
        run: |
          docker build -t login-app . || (echo "Docker build failed!" && exit 1)
          docker images  # List all available images to ensure 'login-app' exists

      # Step 5: Tag the Docker image
      - name: Tag the Docker image
        run: |
          docker tag login-app ${{secrets.DOCKER_USERNAME}}/login-app
          docker images  # Verify that login-app is tagged correctly

      # Step 6: Push the Docker image to Docker Hub
      - name: Push the Docker image to Docker Hub
        run: |
          docker push ${{secrets.DOCKER_USERNAME}}/login-app
