name: Streamlit Login App (Running on the local machine)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checking the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Setting up the docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      #login in the docker hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      #building the docker image
      - name: Build the Docker image
        run: |
          docker build -t login-app . || (echo "Docker build failed!" && exit 1)

      # Tagging the docker image
      - name: Tag the Docker image
        run: |
          docker tag login-app:latest "${{ secrets.DOCKER_USERNAME }}/login-app:latest"

      # Pushing the docker image
      - name: Push the Docker image to Docker Hub
        run: |
          docker push "${{ secrets.DOCKER_USERNAME }}/login-app:latest"
