name: Streamlit Login App (Running on the local machine)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Step 3: Build the Docker image
      - name: Build the Docker image
        run: |
          docker build -t login-app .

      # Step 4: Test the Docker container
      - name: Test the Docker image
        run: |
          docker run -d -p 8501:8501 login-app
